# This is a basic workflow to help you get started with Actions

# Dreg's note: this is the big craaap in the world xD

name: CI

# Controls when the workflow will run
on:
  # Triggers the workflow on push or pull request events but only for the "main" branch
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v3

      - name: Error if exist tab char
        run: find . -iregex '.*\.\(asm\|txt|rap|md\)' | xargs -n 1 sh -c 'echo $0 && xxd -p $0 | tr -d "\n" | grep -v "09" || exit 255' 

      - name: Error if .asm files are not crlf ended
        run: find . -iregex '.*\.\(asm\|txt|rap|md\)' | xargs -n 1 sh -c 'echo $0 && xxd -p $0 | tr -d "\n" | grep -vP "(?<!0d)0a" || exit 255' 

      - name: Error if exist trailing chars 0d
        run: find . -iregex '.*\.\(asm\|txt|rap|md\)' | xargs -n 1 sh -c 'echo $0 && xxd -p $0 | tr -d "\n" | grep -v "200d" || exit 255' 

      - name: wine
        run: sudo dpkg --add-architecture i386 && sudo apt-get update && sudo apt-get -y install wine wine32:i386 && export WINEPREFIX=~/.wine && WINEARCH=win32 winecfg
        
      - name: build cerdalux & run
        run: git clone https://github.com/therealdreg/dregs-masm32-wine.git && cd dregs-masm32-wine && cp ../source/cerdalux.asm programs/cerdalux.asm && sed -i 's/\\masm32\\include/libs/g' programs/cerdalux.asm  && sed -i 's/\\masm32\\macros/libs/g' programs/cerdalux.asm  &&  sed -i 's/\\masm32\\lib/libs/g' programs/cerdalux.asm && ./masm32.sh cerdalux && ! grep -q -w -E -i ".*cerdalux.*such file or directory" logmasm32.log
